@startuml

skinparam classBackgroundColor white

interface ITelemetry  {
    +start(): void
    +stop(): void
    +get_telemetry(): TelemetryData
}

interface IMovementSimulator {
    +start(): void
    +stop(): void
    +get_xy(): Point2D
}

dataclass Point2D <<(D, lightblue)>> {
    + x: float
    + y: float
}


dataclass TelemetryData <<(D, lightblue)>> {
    + pose: Pose
    + battery: Battery
}


class DroneTelemetry {
    - _drone_ip: str
    - _drone_port: int
    - _local_port: int
    - _telemetry: TelemetryData
    - _simulator: IMovementSimulator

    + DroneTelemetry(drone_ip: str, drone_port: int, local_port: int, simulator: IMovementSimulator)
    + get_simulator(): IMovementSimulator
    - _start_communication(): void
    - _send_handshake(): void
    - _process_battery_packet(payload: bytes): void
    - _process_pose_packet(payload: bytes): void
    - _listen(): void
}

ITelemetry <|.. DroneTelemetry
DroneTelemetry --> TelemetryData
DroneTelemetry --> Point2D
IMovementSimulator <-* DroneTelemetry

@enduml

