
skinparam classBackgroundColor white

dataclass FrameWithTelemetry <<(D, lightblue)>> {
    + frame: Frame
    + telemetry: TelemetryData
}

abstract class AFrameConsumer <<(A, LightCoral)>> {
    - _queue: Queue<FrameWithTelemetry>
    {abstract} +start(): void
    {abstract} +stop(): void
    +enqueue(fwt: FrameWithTelemetry): void
    {abstract}-_process_frame(fwt: FrameWithTelemetry): Any
}

class Viewer {
    - _loop(): void
}

AFrameConsumer <|.. Viewer
Viewer -> FrameWithTelemetry

@enduml