@startuml

skinparam classBackgroundColor white

interface ITelemetry  {
    +start(): void
    +stop(): void
    +get_telemetry(): TelemetryData
}

interface ICamera {
    +start(): void
    +stop(): void
    +get_frame(): Frame
    +turn_on_flash(): void
    +turn_off_flash(): void
}

abstract class AFrameConsumer <<(A, LightCoral)>> {
    - _queue : Queue<FrameWithTelemetry>
    {abstract} +start(): void
    {abstract} +stop(): void
    +enqueue(fwt: FrameWithTelemetry): void
    {abstract}-_process_frame(fwt: FrameWithTelemetry): Any
}

dataclass TelemetryData <<(D, lightblue)>> {
    + pose: Pose
    + battery: Battery
}


class Matcher {
    - _telemetry: ITelemetry
    - _camera: ICamera
    - _consumers: List<AFrameConsumer>
    + Matcher(telemetry: ITelemetry, camera: ICamera)
    + start(): void
    + stop(): void
    + register_consumer(consumer: AFrameConsumer): void
    - _match(): void
}

ITelemetry <--* Matcher
ICamera <--* Matcher
AFrameConsumer <--* Matcher
Matcher -> TelemetryData
@enduml

