
skinparam classBackgroundColor white

dataclass Battery <<(D, lightblue)>>{
    + voltage: float
}

dataclass Position <<(D, lightblue)>> {
    + x: float
    + y: float
    + z: float
}

dataclass Orientation  <<(D, lightblue)>> {
    + roll: float
    + pitch: float
    + yaw: float
}

dataclass Pose <<(D, lightblue)>> {
    + position: Position
    + orientation: Orientation
}

dataclass TelemetryData <<(D, lightblue)>> {
    + pose: Pose
    + battery: Battery
}

dataclass Frame <<(D, lightblue)>> {
    + data: np.ndarray
}

dataclass FrameWithTelemetry <<(D, lightblue)>> {
    + frame: Frame
    + telemetry: TelemetryData
}

abstract class AFrameConsumer <<(A, LightCoral)>> {
    - _queue: Queue<FrameWithTelemetry>
    {abstract} +start(): void
    {abstract} +stop(): void
    +enqueue(fwt: FrameWithTelemetry): void
    {abstract}-_process_frame(fwt: FrameWithTelemetry): Any
}

class Viewer {
    - _loop(): void
}

AFrameConsumer <|.. Viewer
Pose *-- Position
Pose *-- Orientation
TelemetryData *-- Pose
TelemetryData *-- Battery
FrameWithTelemetry *-- Frame
FrameWithTelemetry *-- TelemetryData
Viewer -> FrameWithTelemetry

@enduml